version: '3.7'

services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - b2c-network

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    networks:
      - b2c-network

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - b2c-network

  b2c-api:
    image: b2c-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - kafka
      - zookeeper
    networks:
      - b2c-network

networks:
  b2c-network:
    driver: bridge
