version: '3.7'

services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - tanda-network

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
    networks:
      - tanda-network

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - tanda-network

  b2c-api:
    image: b2c-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tanda-b2c-api
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - kafka
      - zookeeper
    networks:
      - tanda-network
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/b2c-api
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

networks:
  tanda-network:
    driver: bridge